// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIlRRsUCbt2Oiniveu5ociKLFBpfUuxE',
    appId: '1:862698581046:web:1e4e05470d007c64a1bc97',
    messagingSenderId: '862698581046',
    projectId: 'my-final-project-5f34f',
    authDomain: 'my-final-project-5f34f.firebaseapp.com',
    storageBucket: 'my-final-project-5f34f.firebasestorage.app',
    measurementId: 'G-8EEET5PZ6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClk-vuZ6bPsJa3S8YbfmKlr7O0Wr7bsKc',
    appId: '1:862698581046:android:b64c1d162e77b1e2a1bc97',
    messagingSenderId: '862698581046',
    projectId: 'my-final-project-5f34f',
    storageBucket: 'my-final-project-5f34f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfiakPzvSbjUfJ_VQWIZtEoJL-QoiKaUQ',
    appId: '1:862698581046:ios:fca73d2ff3bd3e8aa1bc97',
    messagingSenderId: '862698581046',
    projectId: 'my-final-project-5f34f',
    storageBucket: 'my-final-project-5f34f.firebasestorage.app',
    iosBundleId: 'com.example.fashionhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfiakPzvSbjUfJ_VQWIZtEoJL-QoiKaUQ',
    appId: '1:862698581046:ios:fca73d2ff3bd3e8aa1bc97',
    messagingSenderId: '862698581046',
    projectId: 'my-final-project-5f34f',
    storageBucket: 'my-final-project-5f34f.firebasestorage.app',
    iosBundleId: 'com.example.fashionhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIlRRsUCbt2Oiniveu5ociKLFBpfUuxE',
    appId: '1:862698581046:web:0842533ada432149a1bc97',
    messagingSenderId: '862698581046',
    projectId: 'my-final-project-5f34f',
    authDomain: 'my-final-project-5f34f.firebaseapp.com',
    storageBucket: 'my-final-project-5f34f.firebasestorage.app',
    measurementId: 'G-2074ZCBBB0',
  );
}
